:- ['common_tests.pl'].
:- ['integer_tests.pl'].
:- ['float_tests.pl'].
:- ['lexer_tests_whitespaces.pl'].
:- ['lexer_tests_booleans.pl'].
:- ['lexer_tests_integers.pl'].
:- ['lexer_tests_floats.pl'].
:- ['lexer_tests_strings.pl'].
:- ['lexer_tests_keywords.pl'].
:- ['lexer_tests_misc.pl'].
:- ['lexer_tests_lexer_from_file.pl'].
